# Generated by Django 6.0.2 on 2026-03-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
